; =============================================================================
;  platformio.ini — FPV Racer RC Firmware
; =============================================================================

[env:rc_p1]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600
build_flags   =
    -D RC_ID=1
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192

lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.14.5

[env:rc_p2]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600
build_flags   =
    -D RC_ID=2
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192

lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.14.5
